name: Run e2e Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run e2e Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: docker
          POSTGRES_USER: docker
          POSTGRES_DB: apisolid
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:e2e
        env:
          JWT_SECRET: testing_secret
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
